version: '3.3'
services:
  bitbucket:
    #image: atlassian/stash:3.6 # For upgrade Change to atlassian/bitbucket-server:7.2.2 from atlassian/stash:3.6
    image: atlassian/bitbucket-server:7.2.2 # For upgrade Change to atlassian/bitbucket-server:7.2.2 from atlassian/stash:3.6
    container_name: bitbucket
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.bitbucket-redirect-websecure.redirectscheme.scheme=https" # <--- New middleware for redirect of http
      # Web
      - "traefik.http.routers.router1.middlewares=bitbucket-redirect-websecure"             # <--- Whenever web entrypoint is hit redirect to websecure
      - "traefik.http.routers.router1.rule=Host(`$SERVER_PROXY_NAME`)"
      - "traefik.http.routers.router1.entrypoints=web"
      - "traefik.http.routers.router1.service=bitbucket-web"
      - "traefik.http.services.bitbucket-web.loadbalancer.server.port=7990"
      # SSH
      - "traefik.tcp.routers.router2.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.router2.entrypoints=bitbucket-ssh"
      - "traefik.tcp.routers.router2.service=bitbucket-ssh"
      - "traefik.tcp.services.bitbucket-ssh.loadbalancer.server.port=7999"
      # Web Secure
      - "traefik.http.routers.router3.rule=Host(`$SERVER_PROXY_NAME`)"
      - "traefik.http.routers.router3.tls=true"
      - "traefik.http.routers.router3.entrypoints=websecure"
      - "traefik.http.routers.router3.service=bitbucket-websecure"
      - "traefik.http.services.bitbucket-websecure.loadbalancer.server.port=7990"
    # You must uncomment the ports if you are NOT running Traefik.
    #ports:
    #  - "7990:7990"
    #  - "7999:7999"
    environment:
      SERVER_PROXY_NAME: ${SERVER_PROXY_NAME} # <--- This must be exported to the environment for bitbucket
      SERVER_PROXY_PORT: ${SERVER_PROXY_PORT} # <--- This must be exported to the environment for bitbucket
      SERVER_SCHEME: ${SERVER_SCHEME}         # <--- This must be exported to the environment for bitbucket
      SERVER_SECURE: ${SERVER_SECURE}         # <--- This must be exported to the environment for bitbucket
      JVM_MINIMUM_MEMORY: ${JVM_MINIMUM_MEMORY:-512m}
      JVM_MAXIMUM_MEMORY: ${JVM_MAXIMUM_MEMORY:-1024m}
    volumes:
      - data:/var/atlassian/application-data/bitbucket #  For upgrade change to /var/atlassian/application-data/bitbucket from /var/atlassian/application-data/stash
    restart: unless-stopped
volumes:
  data: {}