version: '3.3'
services:
  postgres:
    image: postgres:9.3-alpine # For upgrade to 7x version update to 11-alpine.
    container_name: postgres-bitbucket
    ports:
      - ${BITBUCKET_DB_PORT}:5432
    environment:
      POSTGRES_DB: ${BITBUCKET_DB:-bitbucket}
      POSTGRES_USER: ${BITBUCKET_DB_USER:-bitbucket}
      POSTGRES_PASSWORD: ${BITBUCKET_DB_PASSWORD:-""}
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
volumes:
  db: {}
