version: "3.3"

services:

  traefik:
    image: "traefik:v2.2.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"                  # <----------------- New https endpoint
      - "--entrypoints.bitbucket-ssh.address=:7999"
      #- "--providers.file.directory=/etc/traefik/dynamic_conf"  # <----------------- If https uncomment
      #- "--providers.file.watch=true"                           # <----------------- If https uncomment
    restart: unless-stopped
    stop_grace_period: 30s
    depends_on:
      - bitbucket
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "7999:7999"
    volumes:

      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ${BITBUCKET_CERTS_DIR}:/certs/:ro                       # <----------------- If https uncomment
      #- ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro     # <----------------- If https uncomment
